name: Build Latest Docker Image manually

on:
    workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    strategy:
        fail-fast: false
        matrix:
          spark-version: ["3.5.0"]
          latest-version: ["0.1.5"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Build docker images
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push jupyterlab-sparglim
      id: docker_build_jupyterlab_sparglim
      uses: docker/build-push-action@v4
      with:
        build-args: |
            SPARGLIM_VERSION=${{ matrix.latest-version }}
            SPARK_VERSION=${{ matrix.spark-version }}
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile.jupyterlab-sparglim
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab-sparglim:${{ matrix.latest-version }}-spark-${{ matrix.spark-version }}
    -
      name: Build and push sparglim-server
      id: docker_build_sparglim_server
      uses: docker/build-push-action@v4
      with:
        build-args: |
            SPARGLIM_VERSION=${{ matrix.latest-version }}
            SPARK_VERSION=${{ matrix.spark-version }}
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile.sparglim-server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparglim-server:${{ matrix.latest-version }}-spark-${{ matrix.spark-version }}
    -
      name: Build and push jupyterlab-sparglim_latest
      id: docker_build_jupyterlab_sparglim_latest
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: |
            SPARGLIM_VERSION=${{ matrix.latest-version }}
            SPARK_VERSION=${{ matrix.spark-version }}
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile.jupyterlab-sparglim
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab-sparglim:latest
    -
      name: Build and push sparglim-server_latest
      id: docker_build_sparglim_server_latest
      uses: docker/build-push-action@v4
      with:
        build-args: |
            SPARGLIM_VERSION=${{ matrix.latest-version }}
            SPARK_VERSION=${{ matrix.spark-version }}
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: ./docker/Dockerfile.sparglim-server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparglim-server:latest
